# Generated by Django 5.1.15 on 2026-07-01 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('track', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('class_days', models.JSONField(blank=True, default=list)),
                ('class_time', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to='accounts.instructorprofile')),
                ('students', models.ManyToManyField(blank=True, related_name='batches', to='accounts.studentprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='curriculum.course')),
            ],
            options={
                'verbose_name_plural': 'batches',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.course')),
            ],
            options={
                'ordering': ('course', 'order'),
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LabExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('target_descriptor', models.TextField(blank=True)),
                ('reset_required', models.BooleanField(default=False)),
                ('submission_required', models.BooleanField(default=False)),
                ('max_marks', models.PositiveIntegerField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='curriculum.module')),
            ],
            options={
                'ordering': ('module', 'title'),
                'unique_together': {('module', 'slug')},
            },
        ),
    ]
