# Generated by Django 5.1.15 on 2026-07-01 02:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lab_start', models.DateTimeField(blank=True, null=True)),
                ('lab_stop', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('extended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extended_sessions', to='accounts.instructorprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_sessions', to='accounts.studentprofile')),
                ('vm_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_sessions', to='labs.vminstance')),
            ],
            options={
                'ordering': ('-login_at',),
            },
        ),
        migrations.CreateModel(
            name='LabReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_vmid', models.IntegerField()),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('window_start',),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_days', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('quota_minutes_per_day', models.PositiveIntegerField(default=0)),
                ('grace_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='curriculum.batch')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='curriculum.labexercise')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
