# Generated by Django 5.1.15 on 2026-07-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('state', models.CharField(choices=[('free', 'Free'), ('leased', 'Leased')], default='free', max_length=8)),
                ('leased_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('ip',),
            },
        ),
        migrations.CreateModel(
            name='LabTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('source_template_vmid', models.IntegerField()),
                ('role', models.CharField(choices=[('attacker', 'Attacker'), ('target', 'Target')], max_length=16)),
                ('cores', models.PositiveIntegerField(default=1)),
                ('ram_mb', models.PositiveIntegerField(default=1024)),
                ('disk_gb', models.PositiveIntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LabInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('stopped', 'Stopped'), ('expired', 'Expired'), ('error', 'Error')], default='pending', max_length=16)),
                ('provisioning_mode', models.CharField(choices=[('shared', 'Shared'), ('per_student', 'Per student'), ('pod', 'Pod')], default='shared', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('lab_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_instances', to='curriculum.labexercise')),
                ('owner_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_instances', to='curriculum.batch')),
                ('owner_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_instances', to='accounts.studentprofile')),
                ('lab_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_instances', to='labs.labtemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.IntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('attacker', 'Attacker'), ('target', 'Target')], max_length=16)),
                ('proxmox_status', models.CharField(blank=True, max_length=32, null=True)),
                ('source_template_vmid', models.IntegerField(blank=True, null=True)),
                ('mirrored', models.BooleanField(default=False)),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms', to='labs.iplease')),
                ('lab_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='labs.labinstance')),
            ],
            options={
                'ordering': ('lab_instance', 'role'),
            },
        ),
        migrations.AddField(
            model_name='iplease',
            name='vm_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_leases', to='labs.vminstance'),
        ),
    ]
