"""Reuse the APIs' own role-filtered querysets for dashboard aggregation.

Rather than re-implementing role scoping (which risks a dashboard/template
leaking data a role can't see), we instantiate the very same DRF read viewsets
the JSON APIs use and call their ``get_queryset()`` with the live request.
Whatever the API would return for this user is exactly what the dashboard
aggregates over — no more, no less. This is the "reuse, don't reimplement"
guarantee: there is a single source of truth for "what can this role see".

The audit trail had no read API before this step, so ``scoped_audit`` defines
the scoping once here and both the /api/admin/audit endpoint and the
/admin/audit/ template read through it.
"""
from django.db.models import Q

from apps.assessments.api import AssessmentReadViewSet, SubmissionViewSet
from apps.audit.models import AuditLog
from apps.curriculum.api import (
    BatchViewSet,
    CourseViewSet,
    LabExerciseViewSet,
    ModuleViewSet,
)
from apps.scheduling.api import (
    AccessSessionViewSet,
    LabReservationViewSet,
    ScheduleViewSet,
)


def api_queryset(viewset_cls, request):
    """Return ``viewset_cls.get_queryset()`` as if the API were serving ``request``.

    The read viewsets branch only on ``request.user.role`` (never on
    ``self.action``), so a minimal viewset instance with the request bound
    yields the identical role-scoped queryset the endpoint itself would return.
    """
    vs = viewset_cls()
    vs.request = request
    vs.action = "list"
    vs.kwargs = {}
    vs.format_kwarg = None
    return vs.get_queryset()


def scoped_courses(request):
    return api_queryset(CourseViewSet, request)


def scoped_modules(request):
    return api_queryset(ModuleViewSet, request)


def scoped_exercises(request):
    return api_queryset(LabExerciseViewSet, request)


def scoped_batches(request):
    return api_queryset(BatchViewSet, request)


def scoped_schedules(request):
    return api_queryset(ScheduleViewSet, request)


def scoped_sessions(request):
    return api_queryset(AccessSessionViewSet, request)


def scoped_reservations(request):
    return api_queryset(LabReservationViewSet, request)


def scoped_submissions(request):
    return api_queryset(SubmissionViewSet, request)


def scoped_assessments(request):
    return api_queryset(AssessmentReadViewSet, request)


def scoped_audit(request):
    """Role-scoped AuditLog queryset — single source of truth reused by both the
    /api/admin/audit API and the /admin/audit/ template.

    admin      -> every row
    instructor -> rows they generated, OR rows generated by a student in a batch
                  they own (the row's actor is that student's user)
    student / other -> nothing (the API gates students out with 403 before this)
    """
    user = getattr(request, "user", None)
    role = getattr(user, "role", None)
    if role == "admin":
        return AuditLog.objects.all()
    if role == "instructor":
        ip = getattr(user, "instructor_profile", None)
        if ip is None:
            return AuditLog.objects.none()
        return AuditLog.objects.filter(
            Q(actor=user) | Q(actor__student_profile__batches__instructor=ip)
        ).distinct()
    return AuditLog.objects.none()
